### ISSUE TITLE
node_modules\gapi-script\index.js Unexpected token (3:43)

### ISSUE THREAD

**Issue by steeevio** [partnerhero/gapi-script#1]
I get the following error compiling - "node_modules\gapi-script\index.js Unexpected token (3:43)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (3:43)" any ideas what might cause this?

**Comment by LucasAndrad** [comment]
Hey @steeevio, thanks for sharing this.
I'll take a look, but this is the entire message error from your console ? If it isn't, please share the entire message, and if you have, your log error file.

**Comment by blizkreeg** [comment]
@LucasAndrad do you know why we're seeing this error?

**Comment by LucasAndrad** [comment]
Hey @blizkreeg, thank you so much for the feedback.

I'll investigate this error tonight. Can you please also share how you are importing and using the gapi-script functions ? That way I'll try to reproduce this error here. Thanks

**Comment by blizkreeg** [comment]
this is show i'm doing it:

```
import {gapi} from 'gapi-script';

gapi.client.init({
  apiKey: API_KEY,
  clientId: CLIENT_ID,
  discoveryDocs: DISCOVERY_DOCS,
  scope: SCOPES
});

```

i don't see the error when i run my app, i see it when running tests using Jest.

**Comment by LucasAndrad** [comment]
Hey @blizkreeg I think your project doesn't have the [babel-plugin-transform-arrow-functions](https://babeljs.io/docs/en/babel-plugin-transform-arrow-functions) that's why you receive that error, the _"Unexpected token"_ that @steeevio mentioned is the arrow function syntax `() => {}`.

Since this project has only one arrow function, I changed it, so all projects can still use `gapi-script` without babel plugins. So now you can try the new version `0.0.5`, I believe will work just fine. 

Please let me know if that version worked for you. Thanks

**Comment by blizkreeg** [comment]
Hi Lucas, apologies, I haven't had a chance to test it out this week. I will be testing the new version on Monday and will let you know.

**Comment by blizkreeg** [comment]
@LucasAndrad still seeing the error when running tests:
```
Test suite failed to run

    /Users/.../classroom-web/node_modules/gapi-script/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { gapi, gapiComplete } from './gapiScript';
```

I'm not sure it has to do with the use of arrow function.

**Comment by blizkreeg** [comment]
I think it has to do with use of ES modules and not commonjs exports.
